# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
   #providers:
      #  in_memory:
      #      memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            security:  true
            provider: master_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /login
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    encoders:
        Krytek\DataBundle\Entity\Usuario:
            algorithm: bcrypt

    providers:
        master_provider:
            entity:
                class: Krytek\DataBundle\Entity\Usuario

    role_hierarchy:

            ROLE_TRANSFUSIONISTA: ROLE_TRANSFUSIONISTA
            ROLE_MEDICO:          ROLE_MEDICO
            ROLE_ADMIN:           ROLE_ADMIN

    access_control:
          #  - { path: ^/data*, roles: ROLE_ADMIN }
            - { path: ^/data/usuario*, roles: ROLE_ADMIN }
            - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/data*, roles: IS_AUTHENTICATED_FULLY }
            - { path: ^/data/bolsa, roles: ROLE_TRANSFUSIONISTA}
            - { path: ^/data/solicitudtransfusion, roles: ROLE_MEDICO}